name: Sync Organization Main to Personal Repository

on:
  schedule:
    - cron: "0 0 * * *" # 매일 실행
  workflow_dispatch: # 수동 옵션 on

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Personal Repository
        uses: actions/checkout@v2

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/Team-Qampus/Qampus_FE.git

      - name: Fetch Upstream Changes
        run: git fetch upstream

      - name: Merge Upstream Main into Personal Main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push Changes to Personal Repository
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
